### ISSUE TITLE
model: Priority should store an integer rather than a String, and be comparable

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#123]
@nightism Why is `Priority` being stored as a string? `Priority.java` is filled with `Integer.parseInt()`s everywhere just because it is not stored in its more obvious format. You're introducing an unnecessary layer of indirection.

Also:
- Should MESSAGE_PRIORITY_CONSTRAINTS be public?
- Should PRIORITY_VALIDATION_REGEX be public?

**Comment by nightism** [comment]
@pyokagan 
- The reason why I chose to store `Priority` as a string is to prepare for the situation where we may want to use other expressions to represent the `Priority`, such as `important`, `don't care`, etc..
- I think `MESSAGE_PRIORITY_CONSTRAINTS` should be public since this value has the potential to be used outside the class, such as in the parser.
- As for `PRIORITY_VALIDATION_REGEX`, since we already have the isValidPriority method... Emm, I think it can be changed to private for now.

And what changes do you need me to make for the Priority class?

**Comment by pyokagan** [comment]
> we may want to use other expressions

Isn't that a concern of the `Parser`, and not the `Model`?

Anyway, I'm not ruling out having a `Priority(String priority)` _constructor_, but I have a issue of how the internal value is stored as a `private String` (It's not even `final`!)

I mean, already the `UPPER_BOUND` and `LOWER_BOUND` are integers anyway, isn't that a sign that the internal `priority` field needs to be an integer as well? For consistency at least?

**Comment by pyokagan** [comment]
> I think MESSAGE_PRIORITY_CONSTRAINTS should be public since this value has the potential to be used outside the class, such as in the parser.

Eh, can't the parser get the message from `IllegalValueException.getMessage()`?

The reason why I say so is because I don't want so much coupling between classes, especially for trivial things like messages. But I don't feel strongly about that, so I won't insist.

**Comment by pyokagan** [comment]
@nightism What's the status of this issue?
